package com.example.lostescape.Server;

public enum Status {
    LOGIN_SUCCESS, USERNAME_NOT_FOUND, INCORRECT_PASSWORD, ACCOUNT_CREATED_SUCCESSFULLY, ACCOUNT_CREATION_FAILED,
    ACCOUNT_UPDATED_SUCCESSFULLY, ACCOUNT_UPDATE_FAILED, ACCOUNT_DELETION_FAILED, ACCOUNT_DELETED_SUCCESSFULLY,

    HIGH_SCORE_ADDITION_FAILED, HIGH_SCORE_ADDED_SUCCESSFULLY;

    public String getMessage() {
        return null;
    }
}